name: "CD"

on:
  pull_request:
    branches: [ main ]
    types:
      - closed
  push:
    branches: [ main ]

jobs:
  mvn-publish:
    uses: derBobby/java-pipelines/.github/workflows/callable-mvn.yml@main
    with:
      mvn-stage: deploy
      cache: true
    secrets: inherit
  codeql:
    needs: mvn-publish
    uses: derBobby/java-pipelines/.github/workflows/callable-codeql.yml@main
    secrets: inherit